### ISSUE TITLE
Mod: Realistic World Generation

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#1]
![obr6tts](https://cloud.githubusercontent.com/assets/1783166/9743292/670e3416-565d-11e5-875f-36cdd5f96e63.png)
**Mod Name:** Realistic World Generation
**Author:** ted80
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281910-teds-world-gen-mods-realistic-world-gen-alpha-1-3
**Screenshots:**

![i9ysof0](https://cloud.githubusercontent.com/assets/1783166/9743257/47811690-565d-11e5-87c7-4696f0072118.jpg)
![wf4nyhz](https://cloud.githubusercontent.com/assets/1783166/9743258/47818332-565d-11e5-9ec6-71e54ee86b1d.jpg)
![wpuyj2n](https://cloud.githubusercontent.com/assets/1783166/9743262/478497de-565d-11e5-8d73-de631d177c36.jpg)
![9joizad](https://cloud.githubusercontent.com/assets/1783166/9743259/47827184-565d-11e5-898d-e4a1cf39d7f2.jpg)
![ejhidoy](https://cloud.githubusercontent.com/assets/1783166/9743261/47848668-565d-11e5-8d26-13db2f956923.jpg)
![eny8i4d](https://cloud.githubusercontent.com/assets/1783166/9743260/4783c98a-565d-11e5-8bef-e51ae95b8f8e.jpg)
![hpnibsj](https://cloud.githubusercontent.com/assets/1783166/9743263/47924938-565d-11e5-9730-9543d17a8272.jpg)

**Comment by benjamin-pilgrim** [comment]
This looks cool, I think we should add it...

**Comment by BuilderJah** [comment]
If it affects ore spawning at all, then no. But I like the look of it otherwise.
