### ISSUE TITLE
Mod: Ars Magica

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#10]
**Mod Name:** Ars Magica 2
**Author:** Mithion
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292222-ars-magica-2-version-1-4-0-008-updated-february-6

**Requires:**
- AnimationAPI (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289836-animationapi-animate-your-entities-v1-2-3)

**Comment by BuilderJah** [comment]
This is a definite must-have.
