### ISSUE TITLE
Discussion: Day Night Cycle Length

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#105]
How long should days be?
How long should nights be?

**Comment by benjamin-pilgrim** [comment]
I think it would be interesting to play with an ark: survival evolved style long day-night cycle. It would make the game more interesting to play because the nighttime is more of a challenge, but you still have time to build and explore in the daytime.

**Comment by BuilderJah** [comment]
45 minutes day, 15 minutes night sounds good to me. Also Milo is just amazing I mean as anyone else noticed this?

**Comment by ghost** [comment]
I agree with the link enthusiast on both points!
