### ISSUE TITLE
Mod: Big Reactors

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#12]
**Mod Name:** Big Reactors
**Author:** Erogenous Beef
**Link:** http://www.big-reactors.com/#/
**Requires:**
- COHFCore (http://teamcofh.com/)

**Comment by benjamin-pilgrim** [comment]
Not sure how to feel about this mod, it boosts your power so much it lets you skip the mid-end game.

**Comment by BuilderJah** [comment]
I am fine with us leaving this out, so we can instead focus on Extra Utilities power. It'll make getting energy more diverse amongst the group.
