### ISSUE TITLE
Mod: Blood Magic

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#13]
**Mod Name:** Blood Magic
**Author:** WayOfTime
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290532-1-7-10-2-1-6-4-blood-magic-v1-3-3-6-updated-jul

**Comment by benjamin-pilgrim** [comment]
@BuilderJah should probably defend this one... I am not sure how I feel about it.

**Comment by BuilderJah** [comment]
Sam was the one who did Blood Magic last time, so I don't really know if I care too much if it's added or not.
