### ISSUE TITLE
Disable Rapiers

### ISSUE THREAD

**Issue by BuilderJah** [TerraGamingNetwork/TerraCraft-Awakened#28]
We all love rapiers, but god damn. No armour can protect against them, and it's a bit bullshit in pvp. I think we should remove rapiers, and instead focus on other non-armour-piercing weapons that do fucktons of damage.

**Comment by UndeadDuck** [comment]
FUCKING SHIT MATE

**Comment by UndeadDuck** [comment]
BECAUSE YOUR FUCKING SHIT MATE AND THEIR NOT

**Comment by benjamin-pilgrim** [comment]
I agree, without a way to limit them to PvE use only, they become way to overpowered.

**Comment by UndeadDuck** [comment]
I think we should keep them because we all know that ben is going to head for the best armour and he needs to be stopped and JANS FUCKING SHIT MATE

**Comment by AlphaCougar** [comment]
But they were great against armoured enemies!

**Comment by BuilderJah** [comment]
They were, but even Ben's super OP diamond extreme essence armour couldn't resist one blow to the face from my epic rapier.

**Comment by benjamin-pilgrim** [comment]
Struggling to find a method to removing them from the pack, so I suggest we just make it a server rule and leave them in.
