### ISSUE TITLE
Mod: Extra Biomes XL

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#29]
**Mod Name:** Extra Biomes XL
**Author:** Annysia
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282126-extrabiomesxl-universal-3-16-2-for-mc-1-7-10

**Comment by groovyben008** [comment]
I don't think that this will work with Realistic World Gen, which we have already decided we will be using, so unless someone can test and prove me wrong, I doubt this will go in the pack.
