### ISSUE TITLE
Mod: Immersive Engineering

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#30]
**Mod Name:** Immersive Engineering
**Author:** BluSunrize
**Link:** http://www.curse.com/mc-mods/minecraft/231951-immersive-engineering

**Comment by benjamin-pilgrim** [comment]
@BuilderJah @UndeadDuck Can I get an opinion of this mod, since its not one we have had as part of the pack before.

**Comment by BuilderJah** [comment]
Looks cool, but it depends how many people will bother since we have Builcraft and such.
