### ISSUE TITLE
Mod: Mekanism

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#39]
**Mod Name:** Mekanism
**Author:** aidancbrady
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284681-mekanism-v8-1-7-fusion-reactors-5x-ore-duplication

**Comment by ghost** [comment]
Added but we need to remove the digital miner.
