### ISSUE TITLE
Mod: Matter Overdrive Replication

### ISSUE THREAD

**Issue by BuilderJah** [TerraGamingNetwork/TerraCraft-Awakened#45]
![matteroverdrivelogo](https://cloud.githubusercontent.com/assets/1783166/9748080/183c8924-567a-11e5-9517-4e7d089e9ad1.png)
**Mod Name:** Matter Overdrive Replication
**Author:** simeonradivoev
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2398952-wip-beta-1-7-10-matter-overdrive-replication
**Screenshots:**
![shield_screenshot](https://cloud.githubusercontent.com/assets/1783166/9748087/20bedd22-567a-11e5-974c-e5df3ee8f7e0.png)
![stabalized-gravitational-anomaly](https://cloud.githubusercontent.com/assets/1783166/9748090/20c26eb0-567a-11e5-88cc-54087426964b.png)
![transporter-in-action](https://cloud.githubusercontent.com/assets/1783166/9748089/20c1c406-567a-11e5-8419-0502b2bab085.png)
![weapon-station-gui](https://cloud.githubusercontent.com/assets/1783166/9748091/20c3c026-567a-11e5-8b1a-029525f8cd17.png)
![weapon-station-hologram](https://cloud.githubusercontent.com/assets/1783166/9748097/21010206-567a-11e5-9e4f-2996ab5a84d4.png)
![android-station](https://cloud.githubusercontent.com/assets/1783166/9748088/20c0260a-567a-11e5-98a1-45d14b0a2320.png)
![android-station-gui](https://cloud.githubusercontent.com/assets/1783166/9748092/20d0e314-567a-11e5-852f-dd74dbc577b5.png)
![fusion-reactor-cover](https://cloud.githubusercontent.com/assets/1783166/9748093/20d35ffe-567a-11e5-9fd4-3e9b892e40f0.jpg)
![mad-scientist-screenshot](https://cloud.githubusercontent.com/assets/1783166/9748096/20d99090-567a-11e5-9dfc-16c06f49f1f3.png)
![pattern-storage_cluster](https://cloud.githubusercontent.com/assets/1783166/9748094/20d92970-567a-11e5-885f-a37066905a1b.png)
![phaser_third_person](https://cloud.githubusercontent.com/assets/1783166/9748095/20d98f82-567a-11e5-8429-9911bb9f32c1.png)

**Comment by benjamin-pilgrim** [comment]
Looks really cool...
