### ISSUE TITLE
Mod: Nevermine 2: Advent of Ascension

### ISSUE THREAD

**Issue by BuilderJah** [TerraGamingNetwork/TerraCraft-Awakened#53]
**Mod Name:** Nevermine 2: Advent of Ascension
**Author:** Xolova
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286381-aoa-20-new-dimensions-300-mobs-27-bosses-450-items

**Comment by BuilderJah** [comment]
We need at least one mod to add more story and purpose to the game, and the design on this looks pretty cool.

**Comment by benjamin-pilgrim** [comment]
While I have been testing stuff in game, I have been killed so many times, and the noises are really annoying and it spews crap on the ui, so I am removing this mod
