### ISSUE TITLE
Mod: Familiars

### ISSUE THREAD

**Issue by BuilderJah** [TerraGamingNetwork/TerraCraft-Awakened#55]
**Mod Name:** Familiars
**Author:** pitman87
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280199-familiars-new-herobrine-notch-chuck-norris

**Comment by BuilderJah** [comment]
A cool way to give slight boosts unlocked with XP.

**Comment by benjamin-pilgrim** [comment]
Known Conflict with Ars Magica 2
