### ISSUE TITLE
Mod: Thaumcraft

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#56]
**Mod Name:** Thaumcraft
**Author:** Azanor
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-4-2-3-5-updated-2015-2-17

**Addons:**
- Thaumcraft Mob Aspects (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076360-1-7-x-thaumcraft-addon-thaumcraft-mob-aspects)
- Forbidden Magic (#34)

**Comment by BuilderJah** [comment]
Hell yeah. This is a given.
