### ISSUE TITLE
Mod: Tinkers Construct

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#58]
**Mod Name:** Tinkers Construct
**Author:** mDiyo
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287648-tinkers-construct

**Addons:** 
- Tic Tooltips (http://minecraft.curseforge.com/mc-mods/76845-tic-tooltips)
- Extra TiC (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445212-extratic-tinkers-construct-mod-support-add-on)
- Tinkers Mechworks (#60)
- Iguanas Tinkers Tweaks (#61)

**Requires:**
- Mantle (http://minecraft.curseforge.com/mc-mods/74924-mantle)

**Comment by BuilderJah** [comment]
Can you really have TGN modded minecraft without Tinkers'?
