### ISSUE TITLE
Mod: Tinkers Defense

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#59]
**Mod Name:** Tinkers Defense
**Author:** Lance5057
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2327572-tinkers-defense

**Comment by BuilderJah** [comment]
If we remove rapiers, Tinkers Defense can really impact PvP. I'm all for this.
