### ISSUE TITLE
Mod: Iguana Tweaks (Tinkers Construct Addon)

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#61]
**Mod Name:** Iguana Tweaks
**Author:** iguana_man
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks

**Comment by BuilderJah** [comment]
I think we should leave this out, to try and balance weapons a bit. That way we can test out other mod packs' weapons as well, and not be limited to early-game op swords.

**Comment by groovyben008** [comment]
Replacing this suggestion with Tic Tweaks (#74)
