### ISSUE TITLE
Map Mods

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#63]
Which map mod do we want to use?

**Comment by benjamin-pilgrim** [comment]
@TerraGamingNetwork/tgn-staff opinions?

**Comment by BuilderJah** [comment]
Idk

**Comment by ghost** [comment]
http://www.curse.com/mc-mods/minecraft/225179-voxelmap

**Comment by BuilderJah** [comment]
VoxelMap is good. Rei's isn't updated anyway.
