### ISSUE TITLE
Mod: Steve Carts

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#66]
**Mod Name:** Steve Carts
**Author:** Vswe
**Link:** http://www.curse.com/mc-mods/minecraft/228625-steves-carts-2

**Comment by BuilderJah** [comment]
I didn't get time to set up Steve's Carts on the last one, but i've messed around with it before. I'd love to have it in the pack. I'll probably set up some cool mining machines with this, since they're way more awesome than quarries.
