### ISSUE TITLE
Mod: Ztones

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#67]
**Mod Name:** 
**Author:** riciJak
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2221070-ztones-v-2-2-1-decorative-blocks-16x

**Comment by BuilderJah** [comment]
I'm not the decorative type, so this doesn't seem all too exciting to me. It's just using up NEI space in my case.
