### ISSUE TITLE
Mod: JABBA

### ISSUE THREAD

**Issue by BuilderJah** [TerraGamingNetwork/TerraCraft-Awakened#68]
**Mod Name:** JABBA
**Author:** ProfMobius
**Link:** http://www.curse.com/mc-mods/minecraft/jabba

**Comment by BuilderJah** [comment]
Gotta love Jabba. I would like this to be in the pack. Also isn't Milo just amazing!

**Comment by ghost** [comment]
I would like to agree with the Link enthusiast!
And my, isn't Jan the best?
