### ISSUE TITLE
Mod: Camping Mod

### ISSUE THREAD

**Issue by ghost** [TerraGamingNetwork/TerraCraft-Awakened#70]
**Mod Name:** Camping Mod
**Author:** rikmuld
**Link:** http://www.curse.com/mc-mods/minecraft/228460-the-camping-mod#t1:screenshots

**Comment by BuilderJah** [comment]
Ugly-ass bears, but everything else looks pretty cool. It's not a necessity, but i'll probably play around with it if it's added
