### ISSUE TITLE
Mod: Treecapitator

### ISSUE THREAD

**Issue by ghost** [TerraGamingNetwork/TerraCraft-Awakened#71]
**Mod Name:** TreeCapitator
**Author:** bspkrs
**Link:** http://www.curse.com/mc-mods/minecraft/treecapitator

**Comment by BuilderJah** [comment]
Yes

**Comment by benjamin-pilgrim** [comment]
@TerraGamingNetwork/tgn-staff Do we really want this when Tinkers has Lumber Axes?
