### ISSUE TITLE
Mod: Cosmetic Armour

### ISSUE THREAD

**Issue by benjamin-pilgrim** [TerraGamingNetwork/TerraCraft-Awakened#75]
**Mod Name:** Cosmetic Armour
**Author:** dmillerw
**Link:**http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2287519-cosmetic-armor-v1-0-5-because-its-important-to-be

**Comment by BuilderJah** [comment]
Fuck yes.

**Comment by ghost** [comment]
FUCKING YES MATE

**Comment by benjamin-pilgrim** [comment]
Conflicts with one of the other inventory mods, possibly baubles.
