### ISSUE TITLE
Mod: Fossils and Archeology Revival

### ISSUE THREAD

**Issue by BuilderJah** [TerraGamingNetwork/TerraCraft-Awakened#80]
**Mod Name:** Fossils and Archeology Revival
**Authors:** tyranno66, Raptorfarian, Bluestreak52, Robberto08, Nanotyrano, Alexthe666, iLexiconn
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2398119-fossils-and-archeology-revival-build-7-2-1-the

**Comment by ghost** [comment]
Anything to add to the actual game I think is a good idea, like dimensions and this mod because it gives us more to explore and more places to go and find or work towards.

**Comment by ghost** [comment]
This also means the game may be taken slower because this time round I will certainly be taking longer with each mod and more mods and I know I will progress slower than people who just go for one and work hard on it but this way it allows for more game time. Also i want to make a bad ass dino pen

**Comment by BuilderJah** [comment]
"Loads of well-written text about opinion", "Also i want to make a bad ass dino pen".
Kek.

**Comment by BuilderJah** [comment]
Damn, new tags @groovyben008 ?
