### ISSUE TITLE
Mod: Superheroes Unlimited

### ISSUE THREAD

**Issue by TurboNinjaGames** [TerraGamingNetwork/TerraCraft-Awakened#81]
**Mod Name:** Superheroes Unlimited
**Authors:** Tihyo
**Link:** http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287160-1-7-10-superheroes-unlimited-mod-v4-1-1-multi

**Comment by BuilderJah** [comment]
Awesome mod, waaaay too OP.

**Comment by BuilderJah** [comment]
Perhaps we could build a superhero arena where you can do pvp with the suits? Out in the normal world, it seems way too OP with the easy flying etc,

**Comment by benjamin-pilgrim** [comment]
Since we are trying to build the pack for balance, unless we can make them less op, its probably not a good idea to add it in...

**Comment by ghost** [comment]
I think Jan's idea could be a good idea but thats only if people would be interested in actually doing it for high stakes or whatever. Unrelated I also feel that we should build seperate bases and allow moderate theft but not being stupid and taking placed blocks

**Comment by BuilderJah** [comment]
I like that, @UndeadDuck . It gives you a reason to try and hide your stash as well :)
