### ISSUE TITLE
Mod:AE2 EE3 EMC Add-On

### ISSUE THREAD

**Issue by ghost** [TerraGamingNetwork/TerraCraft-Awakened#97]
**Mod Name:** AE2 EE3 EMC Add-On
**Author:** 
**Link:** http://www.curse.com/mc-mods/minecraft/230951-ae2-ee3-emc-add-on

This could be really shit, I didn't really bother to look up on it xD

**Comment by BuilderJah** [comment]
Sure. It's not like it'll take up tons of space anyway
