### ISSUE TITLE
Mod: Recall Stones

### ISSUE THREAD

**Issue by ghost** [TerraGamingNetwork/TerraCraft-Awakened#98]
**Mod Name:** Recall Stones
**Author:** 
**Link:** http://www.curse.com/mc-mods/minecraft/recall-stones#t1:description

**Comment by benjamin-pilgrim** [comment]
Added for now, but this may be replaced by a custom mod at a later date. I dislike the use of ender-pearls as power and the ability to tp to a player after killing them with the right items (makes pvp-trolling way to effective)
